### PR TITLE
Fix apparent swift issues with swift 4

### PR DESCRIPTION
**Pull request by joshglick**
I had issues when cloning so fixed the issues. I'd be happy to find out this is an unnecessary PR.

### CODE REVIEW

**Comment by npmccallum** [comment]
I fixed these in my repo on my computer at home, but I forgot to push them. Also, I'm pretty sure that your attempt at fixing FreeOTP/TokenStore.swift breaks compatibility with anyone using the code from master. This isn't necessarily a deal-breaker because we haven't released this code yet. I'm also not excited to learn that NSCoding seems to be so fragile.

**Comment by joshglick** [comment]
That's good to hear. I thought I was going crazy when I clone and recloned and still had build issues. I'm doing a clean fork to use for a newer project I am working on so i didn't have issues with the token store but happy to try and figure out how to fix that for others.

**Comment by joshglick** [comment]
Or to cancel my PR if you have a working version already that you'd like to push.

**Comment by npmccallum** [comment]
@joshglick What are these new commits?

**Comment by joshglick** [comment]
Sorry! These were pushed to the wrong remote, closing now

**Comment by npmccallum** [comment]
@joshglick I'm still curious what you're working on. Are you able to talk about it?

**Comment by joshglick** [comment]
I actually can’t talk about it quite yet, but I will let you know once we
are ready to make something more public.

**Pull request closed without merging**
