### PR TITLE
Fix camera permission crash on iOS 12

### LINKED ISSUE #112: Free OTP app not working on IOS12.1
Whenever I try to scan a bar code with freeOTP app it just blanks  out and I am not able to get the OTP. I use this in conjunction to RedHat IdM for enabling MFA. I opened case with RedHat support, but I am told to open up an issue here.

### PR DESCRIPTION
**Pull request by sabbaka**
Fixes #112

### CODE REVIEW

**Comment by yohhad5** [comment]
Hi can you please fix the issue, It is not working for me, I use iOS >12. It crash when i try to access the camer.

**Comment by yohhad5** [comment]
Thx for the fix, it is working prfectly.

**Comment by sabbaka** [comment]
> Thx for the fix, it is working prfectly.

I am working on fix for the wide angle camera now. Thanks a lot for the feedback.

**Comment by justin-stephenson** [comment]
This is outdated now.

**Pull request closed without merging**
