### PR TITLE
Fix copying Token code to clipboard

### PR DESCRIPTION
**Pull request by justin-stephenson**

### CODE REVIEW

**Comment by npmccallum** [comment]
Can you give me some background on this? Clipboard support should already exist.

**Comment by justin-stephenson** [comment]
@npmccallum It was removed somewhere along the way, possibly in 3853c2dc5bf114f246b6b3533f24638838fedc92 as I don't see any newly added lines with `UIPasteboard`

**Comment by npmccallum** [comment]
It should be one of the ways you can share a token.

**Comment by justin-stephenson** [comment]
@npmccallum Copying to clipboard through 'Share' still works as expected. 

However, I received feedback from someone stating "when you tapped on a token to expose the token the value would automatically be added to iPhone clipboard". That is the copy functionality this PR is intended to fix.

**Comment by npmccallum** [comment]
At the cost of leaking the token when it isn't needed. That's bad security.

**Comment by justin-stephenson** [comment]
I'll close this one out, thanks for clarification.

**Pull request closed without merging**
