### PR TITLE
Gracefully handle the lack of a camera in Simulator

### PR DESCRIPTION
**Pull request by jeredfloyd**
Prints a useful warning rather than crashing due to an unchecked exception type when tapping the scan button in Simulator.  (Sorry this is on top of my previous changeset, still getting the hang of these tools.)

### CODE REVIEW

**Comment by jtligon** [comment]
Looks like this addressed the review in PR 88.
LGTM

**Comment by npmccallum** [comment]
@jtligon Actually, it doesn't. It just adds the simulator camera fix on top of those changes.

**Comment by jtligon** [comment]
I checked out the PR and the identifiers look good, as well as the print statements, I think the commits were amended?


51df907 has the project file reverts

**Comment by npmccallum** [comment]
I have merged a version of this. See PR #88 for more details.

**Pull request closed without merging**
