### PR TITLE
Added manual add

### LINKED ISSUE #138: Can't do manual entry
Environment: iOS 12.4.4 on iPhone 6. FreeOTP v 1.2 freshly installed from App Store.

Click on plus "+" to do manual entry. I can fill in all the fields but the "Save" button never activates. It remains greyed out and I cannot save the entry.

### PR DESCRIPTION
**Pull request by igor2890**
- Created new manual add screen with functionality
- Added UI tests

Fixes #138

### CODE REVIEW

**Comment by igor2890** [comment]
Hi @justin-stephenson !
I had a problem clearing git commit history, so I made a new pull request.

**Comment by justin-stephenson** [comment]
Hi @igor2890 These changes look good, could you squash the commits into a single "Added manual add" commit? I just need to test this on my older iPhone 8 device then I can ack.

**Comment by justin-stephenson** [comment]
Tested this works on iPhone 8, will merge once code is squashed into a single commit.

**Comment by igor2890** [comment]
Hi @justin-stephenson . Code is squashed.

**Comment by ADASNET** [comment]
When do you expect this to be available in the IOS store?

**Comment by justin-stephenson** [comment]
> When do you expect this to be available in the IOS store?

I will publish a new release in the next couple weeks.

**Pull request merged**
